### ISSUE TITLE
One-Click Inventory

### ISSUE THREAD

**Issue by cstria0106** [Spokeek/awesome-ndmf#6]
Hello,

I would like to introduce [One Click Inventory](https://github.com/weasel-club/OneClickInventory), a system I developed, in hopes of reaching a broader audience and fostering more technical contributions. I kindly request that this project be added to the repository.

One Click Inventory has received 1109 likes on [Booth](https://booth.pm/ko/items/5517179) and is widely used among Korean VRChat users. It is a modular avatar-based inventory system that, while similar to [Modular Avatar](https://modular-avatar.nadena.dev/docs/tutorials/object_toggle) and [VRCFury](https://vrcfury.com/components/toggle/), is specifically optimized for common inventory use cases in VRChat. This optimization allows users to set it up more intuitively through a user-friendly UI.

### Features of One Click Inventory:
- **Automatic Generation of Object Toggles (bool) and Switching (int) Animations**
- **Parameter Compression:**
 While an integer parameter (int) in VRChat typically uses 8 bits, supporting up to 256 states, this is often excessive for scenarios like an inventory with only three outfits. To address this, integer parameters are converted into multiple boolean (bool) parameters through encoding and decoding. This approach allows finer control over the parameter usage, such as using only 2 bits to represent up to 4 states, which is sufficient for selecting among three outfits. [This plugin](https://github.com/raiti-chan/int-parameter-compressor) was inspired by.

- **Menu Creation:**
 Seamlessly integrates with Modular Avatar to support the creation of more complex menus.
- **Icon Generation:**
 Automatically captures menu icons.
- **Advanced Features:**
 Includes options for modifying blendshapes, changing materials, and toggling additional objects on or off.

I look forward to your consideration and hope this tool can be beneficial to the community. Thank you!

**Comment by Spokeek** [comment]
Hello, first of all thank you so much for your submission. This is very well written and that's very nice to read.
I did take some time to read about the project because i never really interacted with people from the Korean community of vrc. 

I gave a try to your project and it feels really promising and to be an easy way to setup outfits and covers a lot of use cases for avatar inventories.

As your project is still in version v0.2.36 , i won't be able to add it to the main list but will definitely add to the Upcoming list.

Thank you again for your work for the community and for your submission. Glad to know another great project making use of NDMF. ✨
